### ISSUE TITLE
CSS伪类是个啥？

### ISSUE THREAD

**Issue by mykurisu** [mykurisu/SomeEXP#2]
css的伪类也称伪类选择器，如果能够了解清楚它的规则，应该会省下很多写JS的时间。

```css
a:link { color: #fff; }
a:visited { color: #fff; }
a:hover { color: #fff; }
a:active { color: #fff; }
```

tips:
a:hover 必须被置于 a:link 和 a:visited 之后，才是有效的。
a:active 必须被置于 a:hover 之后，才是有效的。
上面的css是不是很熟悉，这就是伪类的一种--锚伪类，分别可以用来规定a标签的活动状态，已被访问状态，未被访问状态，和鼠标悬停状态。除了锚伪类，CSS还定义了很多其他的伪类[CSS选择器](http://www.w3school.com.cn/cssref/css_selectors.asp)可谓是琳琅满目，今天注重讲几个博主曾经用过的，以及博主认为比较有用的几个伪类。

#### :focus
在使用input标签时，会遇到这样一个需求，选中输入框时需要输入框出现不同的样式，在没有了解到有这个伪类之前，博主是采取使用JS获取相关输入框再改变其样式。

```html
<input type="text" id="test">
```

```js
let input = document.getElementById("test");
input.style.backgroundColor = "red";
```

这样显然是不够优雅滴，现在让我们看看:focus是怎么样优雅的解决问题的

```css
input:focus {
background-color: red;
}
```

这样也许没啥说服力，但是如果样式多了的话，使用:focus的优势就体现出来了，明显比使用js控制方便许多。

#### :first-child :last-child :nth-child(n)
不知道大家有没碰到过这种需求，一个图片列表，要求每隔两张图片要显示一张不同样式的图片。一开始博主遇到这个需求很苦恼，天真的认为这个需要通过js的循环来解决，但是后面发现其实只需要靠css就能完成这个需求。

:first-child -- 选择属于父元素的第一个子元素
:last-child -- 选择属于父元素的最后一个子元素
:nth-child(n) -- 选择属于其父元素的第n个子元素

假设我们要完成这样的一个页面布局：

<img src="css---1.png" width="70%"/>

首先分析一下布局，应该是一个ul，其中第一张为大图，第二第三张都是小的图片，然后第四张又是和第一张一样的大图。简单来说就是以3为一个周期，所以在使用:nth-child(n)时，n就可以写成3n，就如同以前做数学题一样，当n=1是，就是:nth-child(3)；需要注意的是这里的n是可以写成式子的，所以就有了下面的代码思路：

```css
	.main{
		overflow: hidden;
		display: flex;
		display: -webkit-flex;
		justify-content: center;
		width: 605px;
	}
	ul{
		padding: 0;
		margin: 0;
		list-style: none;
	}
	li:nth-child(3n+1){
		width: 600px;
    	height: 600px;
		margin-bottom: 10px;
		clear: both;
		overflow: hidden;
		-webkit-border-radius: 5px;
		-moz-border-radius: 5px;
		border-radius: 5px;
		box-shadow: 2px 2px 2px #C3C3C3;
		background-color: white;
    	display: flex;
		display: -webkit-flex;
		justify-content: center;
    	align-items: center;
	}
	li:nth-child(3n+2){
		width: 290px;
    	height: 290px;
		background-color: white;
		float: left;
		margin-bottom: 10px;
		-webkit-border-radius: 5px;
		-moz-border-radius: 5px;
		border-radius: 5px;;
		box-shadow: 2px 2px 2px #C3C3C3;
		overflow: hidden;
    	display: flex;
		display: -webkit-flex;
		justify-content: center;
    	align-items: center;
	}
	li:nth-child(3n+3){
		margin-right: 5px;
		width: 290px;
     	height: 290px;
		background-color: white;
		float: right;
		margin-bottom: 10px;
		-webkit-border-radius: 5px;
		-moz-border-radius: 5px;
		border-radius: 5px;;
		box-shadow: 2px 2px 2px #C3C3C3;
		overflow: hidden;
    	display: flex;
		display: -webkit-flex;
		justify-content: center;
    	align-items: center;
	}
```

```html
<div class="main">
	<ul>
		<li>1</li>
		<li>2</li>
		<li>3</li>
		<li>4</li>
	</ul>
</div>
```

这样，一个简约的布局就完成啦。[运行看看?](https://jsfiddle.net/vwpvy8jm/)其中关于nth-child(3n+1)可以很多种写法，博主这只是其中一种而已。

#### :before :after
博主在看别人代码的时候总会看到:before :after这两个东西，当时就很迷惑这是啥？这个有什么用呢？今天就来一起学习一下怎么使用它们吧！

.test:before 在class="test"元素的内容之前插入内容。
.test:after 在class="test"元素的内容之后插入内容。

这个是相对官方的解释，我看完之后还是不知道它们的用处到底是啥，所以还是自己写个例子看看吧！

```html
<style>
p:before {
	content: "加在前面哦";
	color: green;
}
p:after {
	content: "加在后面哦";
	color: red;
}
</style>

<p>这大概是个测试语句</p>
```

运行效果大概是这样

<img src="css---2.png" width="70%"/>

很明显的看到在p标签的前后都出现了不同样式的字，这就是:before和:after最简单的使用方式。但它们就只有这点用处？[远远不止，在:before和:after中是可以使用任何样式的甚至还可以接受背景图片的插入](http://www.hongkiat.com/blog/pseudo-element-before-after/)，但是需要注意的是一定要content: ""哪怕你根本不需要加入字符内容，如果没有content的话这两个伪类是不会起作用的。
